version: '3.8'

services:
  web:
    build: .
    container_name: cupcast_web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - .:/app
    restart: always
